export const productos = [
    {
        id:1,
        marca:"Pan",
        modelo: "Pan francés",
        precio:500,
        stock:70,
        IMG:"../../public/Img/pan.jpg",
    },
    {
        id:2,
        marca:"Pan",
        modelo: "Pan casero",
        precio:600,
        stock:50,
        IMG:"../../public/Img/pan-casero.jpg",
    },
    {
        id:3,
        marca:"Pan",
        modelo: "Pan con semillas",
        precio:650,
        stock:30,
        IMG:"../../public/Img/pan-semilla.jpg",
    },
    {
        id:4,
        marca:"Pan",
        modelo: "Pan integral",
        precio:580,
        stock:35,
        IMG:"../../public/Img/pan-integral.jpg",
    },
    {
        id:5,
        marca:"Torta",
        modelo: "Torta de café",
        precio:2300,
        stock:13,
        IMG:"../../public/Img/torta.jpg",
    },
    {
        id:6,
        marca:"Torta",
        modelo: "Alfajor de maicena",
        precio:1200,
        stock:10,
        IMG:"../../public/Img/alfajor.jpg",
    },
    {
        id:7,
        marca:"Torta",
        modelo: "Cupcakes",
        precio:1600,
        stock:10,
        IMG:"../../public/Img/cupcakes.jpg",
    },
    {
        id:8,
        marca:"Torta",
        modelo: "Facturas",
        precio:1500,
        stock:36,
        IMG:"../../public/Img/facturas.jpg",
    },

]
